version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_CONNECTION=${MONGODB_URI}
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped